name: Build Docker Image ENV

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 90
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Login To Huawei Cloud Docker Registry
        uses: docker/login-action@v1
        with:
          registry: swr.cn-south-1.myhuaweicloud.com
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWD }}
      - name: Prepare Docker Cross Compile
        run: docker run --rm --privileged docker/binfmt:a7996909642ee92942dcd6cff44b9b95f08dad64 && docker buildx create --use --name multi-arch-builder
        timeout-minutes: 10
      - name: Build Docker Backend Server Image
        run: docker buildx build -f Dockerfile --platform linux/arm64 . -t austin-web:local --load
        timeout-minutes: 60
      - name: Push Backend Server Docker Image
        run: docker tag austin-web:local swr.cn-south-1.myhuaweicloud.com/juji-dev/austin-web:$(git rev-parse --short HEAD) && docker push swr.cn-south-1.myhuaweicloud.com/juji-dev/austin-web:$(git rev-parse --short HEAD)
        timeout-minutes: 10
